extends:
  - "prettier"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "prettier"
  - "@typescript-eslint"
  - "html"
env:
  browser: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  prettier/prettier: ["error"]
  # I quite like having explicit type defintiions so disable this rule.
  "@typescript-eslint/no-inferrable-types": "off"
